package Framework;

public class Information {
	
	//States
	private State INVALID = new State("INVALID", 0);
	private State START = new State("START", 1);
	private State F_STATE = new State("F_STATE", 2);
	private State FL_STATE= new State("FL_STATE", 3);
	private State FLO_STATE= new State("FLO_STATE", 4);
	private State FLOA_STATE= new State("FLOA_STATE", 5);
	private State FO_STATE= new State("FO_STATE", 6);
	private State I_STATE= new State("I_STATE", 7);
	private State IN_STATE= new State("IN_STATE", 8);
	private State E_STATE= new State("E_STATE", 9);
	private State EL_STATE= new State("EL_STATE", 10);
	private State ELS_STATE= new State("ELS_STATE", 11);
	private State ELSEI_STATE= new State("ELSEI_STATE", 12);
	private State W_STATE= new State("W_STATE", 13);
	private State WH_STATE= new State("WH_STATE", 14);
	private State WHI_STATE= new State("WHI_STATE", 15);
	private State WHIL_STATE= new State("WHIL_STATE", 16);
	private State OPEN_BRACE = new State("OPEN_BRACE", 17);
	private State CLOSE_BRACE= new State("CLOSE_BRACE", 18);
	private State OPEN_PARAN= new State("OPEN_PARAN", 19);
	private State CLOSE_PARAN= new State("CLOSE_PARAN", 20);
	private State ADD_OP = new State("ADD_OP", 21);
	private State SUBTRACT_OP = new State("SUBTRACT_OP", 22);
	private State MULTIPLY_OP = new State("MULTIPLY_OP", 23);
	private State DIVIDE_OP = new State("DIVIDE_OP", 24);
	private State EXCLAMATION_STATE = new State("EXCLAMATION_STATE", 25);
	private State NOT_EQUAL_OP = new State("NOT_EQUAL_OP", 26);
	private State LT_OP = new State("LT_OP", 27);
	private State LT_ET_OP = new State("LT_ET_OP", 28);
	private State GT_OP = new State("GT_OP", 29);
	private State GT_ET_OP = new State("GT_ET_OP", 30);
	private State ASSIGN_OP = new State("ASSIGN_OP", 31);
	private State EQUALS_OP = new State("EQUALS_OP", 32);
	private State FOR_COND = new State("FOR_COND", 33);
	private State WHILE_COND = new State("WHILE_COND", 34);
	private State IF_COND = new State("IF_COND", 35);
	private State ELSE_COND = new State("ELSE_COND", 36);
	private State ELSE_IF_COND = new State("ELSE_IF_COND", 37);
	private State FLOAT_TYPE = new State("FLOAT_TYPE", 38);
	private State INT_TYPE = new State("INT_TYPE", 39);
	private State IDENTIFIER = new State("IDENTIFIER", 40);
	
	//Array containing all states
	private State[] states = {INVALID,START,F_STATE,FL_STATE,FLO_STATE,FLOA_STATE,FO_STATE,I_STATE,IN_STATE,E_STATE,EL_STATE,ELS_STATE,ELSEI_STATE,W_STATE,WH_STATE,WHI_STATE,WHIL_STATE,OPEN_BRACE,CLOSE_BRACE,OPEN_PARAN,CLOSE_PARAN,ADD_OP,SUBTRACT_OP,MULTIPLY_OP,DIVIDE_OP,EXCLAMATION_STATE,NOT_EQUAL_OP,LT_OP,LT_ET_OP,GT_OP,GT_ET_OP,ASSIGN_OP,EQUALS_OP,FOR_COND,WHILE_COND,IF_COND,ELSE_COND,ELSE_IF_COND,FLOAT_TYPE,INT_TYPE,IDENTIFIER};
	
	//Inputs
	private Input zero = new Input('0', 1);
	private Input one = new Input('1', 2);
	private Input two = new Input('2', 3);
	private Input three = new Input('3', 4);
	private Input four = new Input('4', 5);
	private Input five = new Input('5', 6);
	private Input six = new Input('6', 7);
	private Input seven = new Input('7', 8);
	private Input eight = new Input('8', 9);
	private Input nine = new Input('9', 10);
	private Input lessT = new Input('<', 11);
	private Input greaterT = new Input('>', 12);
	private Input exclamation = new Input('!', 13);
	private Input underscore = new Input('_', 14);
	private Input equal = new Input('=', 15);
	private Input openBrace = new Input('{', 16);
	private Input closeBrace = new Input('}', 17);
	private Input openParan = new Input('(', 18);
	private Input closeParan = new Input(')', 19);
	private Input plus = new Input('+', 20);
	private Input minus = new Input('-', 21);
	private Input asterisk = new Input('*', 22);
	private Input backSlash = new Input('/', 23);
	private Input lowerA = new Input('a', 24);
	private Input upperA = new Input('A', 25);
	private Input lowerB = new Input('b', 26);
	private Input upperB = new Input('B', 27);
	private Input lowerC = new Input('c', 28);
	private Input upperC = new Input('C', 29);
	private Input lowerD = new Input('d', 30);
	private Input upperD = new Input('D', 31);
	private Input lowerE = new Input('e', 32);
	private Input upperE = new Input('E', 33);
	private Input lowerF = new Input('f', 34);
	private Input upperF = new Input('F', 35);
	private Input lowerG = new Input('g', 36);
	private Input upperG = new Input('G', 37);
	private Input lowerH = new Input('h', 38);
	private Input upperH = new Input('H', 39);
	private Input lowerI = new Input('i', 40);
	private Input upperI = new Input('I', 41);
	private Input lowerJ = new Input('j', 42);
	private Input upperJ = new Input('J', 43);
	private Input lowerK = new Input('k', 44);
	private Input upperK = new Input('K', 45);
	private Input lowerL = new Input('l', 46);
	private Input upperL = new Input('L', 47);
	private Input lowerM = new Input('m', 48);
	private Input upperM = new Input('M', 49);
	private Input lowerN = new Input('n', 50);
	private Input upperN = new Input('N', 51);
	private Input lowerO = new Input('o', 52);
	private Input upperO = new Input('O', 53);
	private Input lowerP = new Input('p', 54);
	private Input upperP = new Input('P', 55);
	private Input lowerQ = new Input('q', 56);
	private Input upperQ = new Input('Q', 57);
	private Input lowerR = new Input('r', 58);
	private Input upperR = new Input('R', 59);
	private Input lowerS = new Input('s', 60);
	private Input upperS = new Input('S', 61);
	private Input lowerT = new Input('t', 62);
	private Input upperT = new Input('T', 63);
	private Input lowerU = new Input('u', 64);
	private Input upperU = new Input('U', 65);
	private Input lowerV = new Input('v', 66);
	private Input upperV = new Input('V', 67);
	private Input lowerW = new Input('w', 68);
	private Input upperW = new Input('W', 69);
	private Input lowerX = new Input('x', 70);
	private Input upperX = new Input('X', 71);
	private Input lowerY = new Input('y', 72);
	private Input upperY = new Input('Y', 73);
	private Input lowerZ = new Input('z', 74);
	private Input upperZ = new Input('Z', 75);
	
	//Array containing all inputs
	private Input[] inputs = {zero,one,two,three,four,five,six,seven,eight,nine,lessT,greaterT,exclamation,underscore,equal,openBrace,closeBrace,openParan,closeParan,plus,minus,asterisk,backSlash,lowerA,upperA,lowerB,upperB,lowerC,upperC,lowerD,upperD,lowerE,upperE,lowerF,upperF,lowerG,upperG,lowerH,upperH,lowerI,upperI,lowerJ,upperJ,lowerK,upperK,lowerL,upperL,lowerM,upperM,lowerN,upperN,lowerO,upperO,lowerP,upperP,lowerQ,upperQ,lowerR,upperR,lowerS,upperS,lowerT,upperT,lowerU,upperU,lowerV,upperV,lowerW,upperW,lowerX,upperX,lowerY,upperY,lowerZ,upperZ};
	
	//Table
	private int[][] table = {
			{INVALID.getTableIndex(),zero.getTableIndex(),one.getTableIndex(),two.getTableIndex(),three.getTableIndex(),four.getTableIndex(),five.getTableIndex(),six.getTableIndex(),seven.getTableIndex(),eight.getTableIndex(),nine.getTableIndex(),lessT.getTableIndex(),greaterT.getTableIndex(),exclamation.getTableIndex(),underscore.getTableIndex(),equal.getTableIndex(),openBrace.getTableIndex(),closeBrace.getTableIndex(),openParan.getTableIndex(),closeParan.getTableIndex(),plus.getTableIndex(),minus.getTableIndex(),asterisk.getTableIndex(),backSlash.getTableIndex(),lowerA.getTableIndex(),upperA.getTableIndex(),lowerB.getTableIndex(),upperB.getTableIndex(),lowerC.getTableIndex(),upperC.getTableIndex(),lowerD.getTableIndex(),upperD.getTableIndex(),lowerE.getTableIndex(),upperE.getTableIndex(),lowerF.getTableIndex(),upperF.getTableIndex(),lowerG.getTableIndex(),upperG.getTableIndex(),lowerH.getTableIndex(),upperH.getTableIndex(),lowerI.getTableIndex(),upperI.getTableIndex(),lowerJ.getTableIndex(),upperJ.getTableIndex(),lowerK.getTableIndex(),upperK.getTableIndex(),lowerL.getTableIndex(),upperL.getTableIndex(),lowerM.getTableIndex(),upperM.getTableIndex(),lowerN.getTableIndex(),upperN.getTableIndex(),lowerO.getTableIndex(),upperO.getTableIndex(),lowerP.getTableIndex(),upperP.getTableIndex(),lowerQ.getTableIndex(),upperQ.getTableIndex(),lowerR.getTableIndex(),upperR.getTableIndex(),lowerS.getTableIndex(),upperS.getTableIndex(),lowerT.getTableIndex(),upperT.getTableIndex(),lowerU.getTableIndex(),upperU.getTableIndex(),lowerV.getTableIndex(),upperV.getTableIndex(),lowerW.getTableIndex(),upperW.getTableIndex(),lowerX.getTableIndex(),upperX.getTableIndex(),lowerY.getTableIndex(),upperY.getTableIndex(),lowerZ.getTableIndex(),upperZ.getTableIndex()},
			{START.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),LT_OP.getTableIndex(),GT_OP.getTableIndex(),EXCLAMATION_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),ASSIGN_OP.getTableIndex(),OPEN_BRACE.getTableIndex(),CLOSE_BRACE.getTableIndex(),OPEN_PARAN.getTableIndex(),CLOSE_PARAN.getTableIndex(),ADD_OP.getTableIndex(),SUBTRACT_OP.getTableIndex(),MULTIPLY_OP.getTableIndex(),DIVIDE_OP.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),E_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),F_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),I_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),W_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{F_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),FL_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),FO_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{FL_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),FLO_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{FLO_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),FLOA_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{FLOA_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),FLOAT_TYPE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{FO_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),FOR_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{I_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IF_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IN_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{IN_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INT_TYPE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{E_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),EL_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{EL_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),ELS_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{ELS_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),ELSE_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{ELSEI_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),ELSE_IF_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{W_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),WH_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{WH_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),WHI_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{WHI_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),WHIL_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{WHIL_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),WHILE_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{OPEN_BRACE.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{CLOSE_BRACE.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{OPEN_PARAN.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{CLOSE_PARAN.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{ADD_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{SUBTRACT_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{MULTIPLY_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{DIVIDE_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{EXCLAMATION_STATE.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),NOT_EQUAL_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{NOT_EQUAL_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{LT_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),LT_ET_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{LT_ET_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{GT_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),GT_ET_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{GT_ET_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{ASSIGN_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),EQUALS_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{EQUALS_OP.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex()},
			{FOR_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{WHILE_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{IF_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{ELSE_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),ELSEI_STATE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{ELSE_IF_COND.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{FLOAT_TYPE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{INT_TYPE.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
			{IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),INVALID.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex(),IDENTIFIER.getTableIndex()},
	};
	
	/**
	 * Method Name: getStates
	 * Purpose: Get array of all states
	 * Parameters: N/A
	 * Preconditions: N/A
	 * Postconditions: Returns an array of all states
	 * Exceptions: N/A
	 */
	public State[] getStates() {
		return states;
	}
	
	/**
	 * Method Name: getNumberOfStates
	 * Purpose: Gets the # of states
	 * Parameters: N/A
	 * Preconditions: N/A
	 * Postconditions: Returns the states array's length
	 * Exceptions: N/A
	 */
	public int getNumberOfStates() {
		return states.length;
	}
	
	/**
	 * Method Name: getInputs
	 * Purpose: Get array of all inputs
	 * Parameters: N/A
	 * Preconditions: N/A
	 * Postconditions: Returns an array of all inputs
	 * Exceptions: N/A
	 */
	public Input[] getInputs() {
		return inputs;
	}
	
	/**
	 * Method Name: getNumberOfInputs
	 * Purpose: Gets the # of inputs
	 * Parameters: N/A
	 * Preconditions: N/A
	 * Postconditions: Returns the inputs array's length
	 * Exceptions: N/A
	 */
	public int getNumberOfInputs() {
		return inputs.length;
	}
	
	/**
	 * Method Name: getFSMTable
	 * Purpose: Gets the FSM table
	 * Parameters: N/A
	 * Preconditions: N/A
	 * Postconditions: Returns the state transition table
	 * Exceptions: N/A
	 */
	public int[][] getFSMTable() {
		return table;
	}
	
	/**
	 * Method Name: findInputIndex
	 * Purpose: Determines the table index value of input
	 * Parameters: char input Character to find index in table for
	 * Preconditions: N/A
	 * Postconditions: Returns the table index value of input
	 * Exceptions: N/A
	 */
	public int findInputIndex(char input) {
		for(int i = 0; i < inputs.length; i++) {
			char character = inputs[i].getInput();
			
			if(character == input) {
				System.out.println(character + ": " + inputs[i].getTableIndex());
				return inputs[i].getTableIndex();
			}
		}
		return -1;
	}
	
	/**
	 * Method Name: findState
	 * Purpose: Finds a state using stateIndex
	 * Parameters: int stateIndex The index of a state
	 * Preconditions: N/A
	 * Postconditions: Returns a state matching stateIndex's value
	 * Exceptions: N/A
	 */
	public State findState(int stateIndex) {
		for(int i = 0; i < states.length; i++) {
			State state = states[i];
			
			if(state.getTableIndex() == stateIndex) {
				return state;
			}
		}
		return null;
	}
	
	/**
	 * Method Name: printFSMTable
	 * Purpose: Prints the entire FSM Table
	 * Parameters: N/A
	 * Preconditions: N/A
	 * Postconditions: N/A
	 * Exceptions: N/A
	 */
	public void printFSMTable() {
		for(int i = 1; i < table.length; i++) {
			System.out.print("Row " + i + ": [");
			
			for(int j = 0; j < table[i].length; j++) {
				int stateIndex = table[i][j];
				
				
				for(int k = 0; k < states.length; k++) {
					State state = states[k];
					if(state.getTableIndex() == stateIndex && j != table[i].length - 1) {
						System.out.print(state.getName() + ", ");
					}
					else if(state.getTableIndex() == stateIndex) {
						System.out.print(state.getName());
					}
				}
			}
			System.out.print("]\n");
		}
	}
}