#include "state_table.h"

const int final_states[10] = {OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE, IDENTIFIER, FOR, INT, IF};

//inputs                (          )         [         ]         {         }         f           o            r           I          N           T            
int state_table[14][13] = {
         {START,     OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE,     F,      IDENTIFIER, IDENTIFIER,      I,     IDENTIFIER, IDENTIFIER},
         {START,     OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER,      I,     IDENTIFIER, IDENTIFIER},//OP_PAREN
         {START,     OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER,      I,     IDENTIFIER, IDENTIFIER},//CL_PAREN
         {START,     OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER,      I,     IDENTIFIER, IDENTIFIER},//OP_BRACK
         {START,     OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER,      I,     IDENTIFIER, IDENTIFIER},//CL_BRACK
         {START,     OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER,      I,     IDENTIFIER, IDENTIFIER},//OP_BRACE
         {START,     OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER,      I,     IDENTIFIER, IDENTIFIER},//CL_BRACE
         {START,     OP_PAREN, CL_PAREN, OP_BRACK, CL_BRACK, OP_BRACE, CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER},//IDENTIFIER
         {IDENTIFIER, INVALID, CL_PAREN, INVALID,  CL_BRACK, INVALID,  CL_BRACE, IDENTIFIER,     FO,     IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER},//F
         {IDENTIFIER, INVALID, CL_PAREN, INVALID,  CL_BRACK, INVALID,  CL_BRACE, IDENTIFIER, IDENTIFIER,     FOR   , IDENTIFIER, IDENTIFIER, IDENTIFIER},//FO
         {START,     OP_PAREN, CL_PAREN, INVALID,   INVALID, INVALID,   INVALID, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER},//FOR
         {IDENTIFIER, INVALID, CL_PAREN, INVALID,  CL_BRACK, INVALID,  CL_BRACE,    IF,      IDENTIFIER, IDENTIFIER, IDENTIFIER,     IN,     IDENTIFIER},//I
         {IDENTIFIER, INVALID, CL_PAREN, INVALID,  CL_BRACK, INVALID,  CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER,      INT},  //IN
         {START, INVALID, CL_PAREN, INVALID,  CL_BRACK, INVALID,  CL_BRACE, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER, IDENTIFIER}     //INT
};